### ISSUE TITLE
CallExpression throwing error 

### ISSUE THREAD

**Issue by jared-stilwell** [jared-stilwell/escomplex#17]
_Reposted from https://github.com/jared-stilwell/escomplex-ast-moz/issues/88_

<blockquote>
Whenever I run the following code:

const file = fs.readFileSync(filePath);
const ast = esprima.parse(file, {range: true, comment: true});
const escomplexResult = escomplex.analyse(ast, escomplexWalker);

an the code has CallExpressions I get the following error: http://imgur.com/xTcEDzN

This code was previously working for me
</blockquote>
<blockquote>
This fixed the issue :

const ast = esprima.parse(file, {loc: true, range: true, comment: true});

The indication that the walker needs the loc option should be indicated.
</blockquote>

**Comment by jared-stilwell** [comment]
@CMatias I added a rough regression test to try to reproduce this issue. While it would be easy to assume the restructuring of the project that occurred in the 2.0.0-alpha release resolved this issue, it seems more likely that I'm not properly representing it in the unit test. Do you mind having a look?

**Comment by jared-stilwell** [comment]
Going to close this for now since I can't reproduce the issue. Please reopen with additional details about how to reproduce the issue.

**Comment by CMatias** [comment]
Hi Jared, sorry for the long radio silence.

The "bug" I was getting was simply being caused by not passing the _loc_ option to the esprima parsing. In the newer version you don't require an ast but rather a path for a file and the parsing is made always with _loc_ so this won't ever happen :)

For my project I need to do a custom parse of an ast besides the escomplex calculation and the previous version (1.3 I think) suited my needs better than the newer version since if I update escomplex I need to double the work on getting the ast. I think there should be an option which includes the walker but lets the user supply the ast.
